### ISSUE TITLE
json.decoder.JSONDecodeError: Extra data: line 1 column 7 (char 6)

### ISSUE THREAD

**Issue by ZeroParadoxHome** [ImanMontajabi/CF_dns_manager#2]
سلام من موقع اجرا کردن فایل ها
هم با ترموکس هم با cmd ویندوز به این ارور بر میخورم
ممنون میشم یه بررسی بکنی

Traceback (most recent call last):
  File "/storage/emulated/0/Download/CF DNS Manager/create_ip.py", line 15, in <module>
    iplist_to_iptext()
  File "/storage/emulated/0/Download/CF DNS Manager/create_ip.py", line 12, in iplist_to_iptext
    iplist = scan_to_iplist()
             ^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/Download/CF DNS Manager/create_ip.py", line 7, in scan_to_iplist
    data = json.load(f)
           ^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 7 (char 6)
![IMG_20230319_184915_723](https://user-images.githubusercontent.com/77263046/226186015-7849eaa8-a330-4bed-8014-b57b322123ec.jpg)

**Comment by ImanMontajabi** [comment]
فایل user_id رو نمیتونه بخونه. کلا پوشه رو پاک کن از اول و عینا مثل فیلم و توضیح تو کانال برو

**Comment by ZeroParadoxHome** [comment]
حله تا ببینم چی میشه
